apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-web-deployment
spec:
  selector:
    matchLabels:
      app: client-web
  replicas: 1
  template:
    metadata:
      labels:
        app: client-web
    spec:
      containers:
        - name: client-web
          image: us-central1-docker.pkg.dev/doji-stg/stg-doji-docker-artifact/doji-client-web:latest
          env:
            - name: ENVIRONMENT
              value: 'staging'
            - name: DOJI_ENV
              value: 'staging'
            - name: BACKEND_ADDRESS
              value: 'https://api.staging.doji.co'
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 240
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 240
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
