apiVersion: "v1"
kind: "Service"
metadata:
  name: "infra-test-web-service"
  namespace: "default"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "infra-test-web"
  type: "LoadBalancer"
  loadBalancerIP: ""