apiVersion: "v1"
kind: "Service"
metadata:
  name: "infra-test-web-service"
  namespace: "default"
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
    - name: "80-to-3000-tcp"
      protocol: "TCP"
      port: 80
      targetPort: 3000
    - name: "443-to-3000-tcp"
      protocol: "TCP"
      port: 443
      targetPort: 3000
  selector:
    app: "infra-test-web"
  type: "LoadBalancer"
  loadBalancerIP: ""
