steps:

#  - name: 'node:18.13.0'
#    entrypoint: 'npm'
#    args:
#      - 'install'
#    id: NpmInstall
#
#  - name: 'node:18.13.0'
#    entrypoint: 'npm'
#    args:
#      - 'run'
#      - 'build'
#    waitFor:
#      - NpmInstall
#    id: NpmBuild
#
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - '--no-cache'
#      - '-t'
#      - '$_CONTAINER_REPOSITORY/$REPO_NAME:$SHORT_SHA'
#      - .
#      - '-f'
#      - Dockerfile
#    waitFor:
#      - NpmBuild
#    id: Build
#
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - push
#      - '$_CONTAINER_REPOSITORY/$REPO_NAME:$SHORT_SHA'
#    waitFor:
#      - Build
#    id: Push

#  - name: 'ubuntu'
#    args: [ 'bash','-c','sed -i "s,DOCKER_IMAGE,us-central1-docker.pkg.dev/doji-stg/stg-doji-docker-artifact/infra-test-web:b630d40," $_K8S_FILES/deployment.yaml' ]
#    id: 'set test core image in yamls'


  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - '--filename=$_K8S_FILES'
      - '--image=$_IMAGE'
      - '--location=$_CLOUD_RUN_REGION'
      - '--cluster=$_CLOUD_CLUSTER_NAME'
#    waitFor:
#      - Push
    id: Deploy

#images:
#  - '$_CONTAINER_REPOSITORY/$REPO_NAME:$SHORT_SHA'
#  - '$_CONTAINER_REPOSITORY/$REPO_NAME:latest'
options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _CONTAINER_REPOSITORY: ''
  _CLOUD_RUN_REGION: ''
  _CLOUD_CLUSTER_NAME: ''
  _K8S_FILES: ''
  _SECRET_SSH_KEY: ''
  _IMAGE: ''

